use bookstore;

-- Retieving all books in 'Fiction' genre --
select * from Books where Genre='Fiction';

-- Retieving all books Published after 1950--
select * from Books where Published_year>1950;

-- Retieving all customers from Canada--
select * from customers where Country='Canada';

-- Retieving Orders placed in November 2023--
select * from orders where Order_Date between '2023-11-01' and '2023-11-30';

-- Retieving the Total Stocks of books available--
select sum(stock) as Total_Stock from Books;

-- Details of the most expensive book--
select * from Books order by Price DESC limit 1;

-- All the customers who ordered more than 1 Quantity of book--
select * from orders where Quantity>1;

-- Retieving Orders where the total amount exceeds $20--
select * from orders where Total_Amount>20;

-- List of all Genres in Books Table--
select DISTINCT Genre from books  ;

-- Book with lowest Stock--
select * from books order by stock limit 1; 

-- Total Revenue Generated by all Orders--
select sum(Total_Amount) as Total_Revenue_Generated from orders;
